### ISSUE TITLE
Unknown Issue raised on fresh image

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-docker#2]
Just deployed the latest abaplint from docker hub.

As it is a fresh image, it tries to load the default config finds an issue (unknown) and stops.

`de version:     v12.16.3
abaplint version: 2.33.3
Using default config
generic[1, 1] - Error: No files found (error)
abaplint: 1 issue(s) found, 0 file(s) analyzed
`

Is there some initial config missing?

**Comment by larshp** [comment]
the default configuration assumes the input files are in /src/, in which folder is your files placed?

**Comment by ed-holland** [comment]
I used the examples in the documentation to deploy the docker image. No src provided. Can you enlight me and i will extend the documention for the next newbe like me.
Setting up Gitlab-ce also and would appreciate some examples for the integration.

**Comment by larshp** [comment]
I have not tried the docker image, perhaps @sbcgua can help?

**Comment by sbcgua** [comment]
Mmmm, not sure I understood the issue. @ed-holland could you pls clarify what exactly are you trying to do ?

An working examplefor gitlab should be here - https://github.com/abaplint/abaplint-docker/blob/master/templates/.gitlab-ci.yml (at least it was working at commit time :) ) and here https://gitlab.com/atsybulsky/abaplinted_sample

**Comment by sbcgua** [comment]
Also check this - https://github.com/abaplint/abaplint/tree/master/docs/ci (maybe makes sense to cross link in this repo too ...)

**Comment by ed-holland** [comment]
The combination of links worked for me. My undestanding of running the checks was wrong (thought it as a service). For the checks, a container is started which performs the checks and completes and is removed.

Will now recreate the whole setup from scratch and start documenting.

**Comment by larshp** [comment]
so this issue can be closed?

feel free to open new issues with questions/comments/suggestions

**Comment by ed-holland** [comment]
Thx. Recreation was successfull. Closing Ticket.
