### ISSUE TITLE
Image not updating

### ISSUE THREAD

**Issue by Zeatynis** [abaplint/abaplint-docker#7]
Hi,
![obraz](https://user-images.githubusercontent.com/9119187/204553035-a184c41f-6401-4286-951c-164ea3670460.png)
![obraz](https://user-images.githubusercontent.com/9119187/204553093-28c8d7ea-6ad1-4e97-84d5-dcbf6faa1c6e.png)

could you publish newest version, please? 😃

**Comment by larshp** [comment]
github actions stops every 90 days, should be running again

**Comment by Zeatynis** [comment]
Seems like the test hasn't passed. The Image action wasn't created.

**Comment by Zeatynis** [comment]
Thanks a lot!
![obraz](https://user-images.githubusercontent.com/9119187/204556601-2bbca7df-5d08-419c-b217-0610e11d5a80.png)
